name: Android-Build

on:
  workflow_dispatch:

jobs:
  buildAndroid:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5

      - name: Install Haxelib Libs
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp --quiet
          haxelib install lime 8.1.2 --quiet
          haxelib install openfl 9.3.2 --quiet
          haxelib install flixel --quiet
          haxelib install flixel-addons --quiet
          haxelib install flixel-ui --quiet
          haxelib install hscript --quiet
          haxelib install hxCodec --quiet

          # Mirrors est√°veis para Psych / Kade / Nightmare
          haxelib git polymod https://github.com/ShadowMario/polymod
          haxelib git linc_luajit https://github.com/ShadowMario/linc_luajit

      - name: Setup Android
        run: |
          yes | haxelib run lime setup android

      - name: Build APK
        run: |
          haxelib run lime build android -release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Build-APK
          path: export/release/android/bin/app.apk
